# name: "Dev Release: Build and Push Docker Image to DockerHub"

# on:
#   push:
#     branches:
#       - "dev"

# jobs:
#   push-base-docker-image:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Branch Checkout
#         uses: actions/checkout@v2
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v2
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#       - name: Build and push
#         uses: docker/build-push-action@v3
#         with:
#           context: .
#           file: ./DockerFiles/base-Dockerfile
#           push: true
#           tags: ${{ secrets.DOCKERHUB_USERNAME }}/offat-base:dev
#           platforms: linux/amd64,linux/arm64

#   push-cli-docker-image:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Branch Checkout
#         uses: actions/checkout@v2
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v2
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#       - name: Build and push
#         uses: docker/build-push-action@v3
#         with:
#           context: .
#           file: ./DockerFiles/cli-Dockerfile
#           push: true
#           tags: ${{ secrets.DOCKERHUB_USERNAME }}/offat:dev
#           platforms: linux/amd64,linux/arm64
